sudo: false
language: python

dist: xenial

env:
  global:
    - TEST_DIR=/tmp/sklearn
    - UCI_HTTPS_URL="https://archive.ics.uci.edu/ml/machine-learning-databases"
    - UCI_FTP_URL="ftp://ftp.ics.uci.edu/pub/machine-learning-databases"

branches:
  only:
    - master

install:
  - source build_tools/travis/install.sh
  - if ! wget ${UCI_HTTPS_URL}/adult/adult.data -P aiflearn/data/raw/adult/ ; then wget ${UCI_FTP_URL}/adult/adult.data -P aiflearn/data/raw/adult/ ; fi
  - if ! wget ${UCI_HTTPS_URL}/adult/adult.test -P aiflearn/data/raw/adult/ ; then wget ${UCI_FTP_URL}/adult/adult.test -P aiflearn/data/raw/adult/; fi
  - if ! wget ${UCI_HTTPS_URL}/adult/adult.names -P aiflearn/data/raw/adult/ ; then wget ${UCI_FTP_URL}/adult/adult.names -P aiflearn/data/raw/adult/; fi
  - if ! wget ${UCI_HTTPS_URL}/statlog/german/german.data -P aiflearn/data/raw/german/ ; then wget ${UCI_FTP_URL}/statlog/german/german.data -P aiflearn/data/raw/german/; fi
  - if ! wget ${UCI_HTTPS_URL}/statlog/german/german.doc -P aiflearn/data/raw/german/ ; then wget ${UCI_FTP_URL}/statlog/german/german.doc -P aiflearn/data/raw/german/; fi
  - wget https://raw.githubusercontent.com/propublica/compas-analysis/master/compas-scores-two-years.csv -P aiflearn/data/raw/compas/

matrix:
  include:
    - env: DISTRIB="conda" PYTHON_VERSION="3.6"
      if: type != cron

script:
  - bash build_tools/travis/test_script.sh

after_success: source build_tools/travis/after_success.sh
