language: python

env:
  global:
    - UCI_HTTPS_URL="https://archive.ics.uci.edu/ml/machine-learning-databases"
    - UCI_FTP_URL="ftp://ftp.ics.uci.edu/pub/machine-learning-databases"

branches:
  only:
    - master

install:
  - pip install -r requirements.txt
  - if ! wget ${UCI_HTTPS_URL}/adult/adult.data -P aiflearn/data/raw/adult/ ; then wget ${UCI_FTP_URL}/adult/adult.data -P aiflearn/data/raw/adult/ ; fi
  - if ! wget ${UCI_HTTPS_URL}/adult/adult.test -P aiflearn/data/raw/adult/ ; then wget ${UCI_FTP_URL}/adult/adult.test -P aiflearn/data/raw/adult/; fi
  - if ! wget ${UCI_HTTPS_URL}/adult/adult.names -P aiflearn/data/raw/adult/ ; then wget ${UCI_FTP_URL}/adult/adult.names -P aiflearn/data/raw/adult/; fi
  - if ! wget ${UCI_HTTPS_URL}/statlog/german/german.data -P aiflearn/data/raw/german/ ; then wget ${UCI_FTP_URL}/statlog/german/german.data -P aiflearn/data/raw/german/; fi
  - if ! wget ${UCI_HTTPS_URL}/statlog/german/german.doc -P aiflearn/data/raw/german/ ; then wget ${UCI_FTP_URL}/statlog/german/german.doc -P aiflearn/data/raw/german/; fi
  - wget https://raw.githubusercontent.com/propublica/compas-analysis/master/compas-scores-two-years.csv -P aiflearn/data/raw/compas/

matrix:
  - python: "3.6"
    before_script:

script:
  - travis_wait pytest tests
